#!/bin/bash
set -euo pipefail

# =============================================================================
# EHDN Downstream Analysis Pipeline
# =============================================================================
# Usage: ./2_ehdn_analysis.sh -i input_file -o output_dir
# The manifest generated by the first EHDN script will be used automatically.
# =============================================================================

# Default values
INPUT_DIR=""
BASE_OUTPUT=""

# Parse input arguments
while getopts "i:o:" opt; do
    case "$opt" in
        i) INPUT_DIR="$OPTARG" ;;
        o) BASE_OUTPUT="$OPTARG" ;;
        *) echo "Usage: $0 -i input_file -o output_dir"; exit 1 ;;
    esac
done

# Check mandatory arguments
if [[ -z "$INPUT_DIR" || -z "$BASE_OUTPUT" ]]; then
    echo "Error: Missing required arguments."
    echo "Usage: $0 -i input_dir -o output_dir"
    exit 1
fi

# Get the directory where this Bash script resides
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Use the manifest generated by the first EHDN script
MANIFEST_FILE="${INPUT_DIR}/ehdn_generated_manifest.tsv"

if [[ ! -f "$MANIFEST_FILE" ]]; then
    echo "Error: Manifest file not found at $MANIFEST_FILE"
    exit 1
fi

# Define paths to scripts relative to this script
PYTHON_SCRIPT="$SCRIPT_DIR/EHDN_raw_call_count_and_tsv.py"
RSCRIPT="$SCRIPT_DIR/count_calls.R"
FILTER_SCRIPT="$SCRIPT_DIR/filter_manifest.py"

# Create output directory if it doesn't exist
mkdir -p "$BASE_OUTPUT"

# Initialize combined log
LOG_FILE="${BASE_OUTPUT}/ehdn_analysis.log"
echo "Starting EHDN downstream analysis at $(date)" > "$LOG_FILE"

# Execute the Python raw call count script
echo "Running raw call count (Python)..." | tee -a "$LOG_FILE"
python3 "$PYTHON_SCRIPT" "$INPUT_DIR" "$BASE_OUTPUT" >> "$LOG_FILE" 2>&1

# Execute the R script for counting calls
echo "Running count_calls (R)..." | tee -a "$LOG_FILE"
Rscript "$RSCRIPT" "$BASE_OUTPUT" >> "$LOG_FILE" 2>&1

# Filter the manifest based on outliers
echo "Filtering manifest based on outliers..." | tee -a "$LOG_FILE"
python3 "$FILTER_SCRIPT" \
    "$BASE_OUTPUT/outliers.tsv" \
    "$MANIFEST_FILE" \
    "$BASE_OUTPUT/filtered_manifest.tsv" \
    "$BASE_OUTPUT/outlier_df.tsv" \
    "$BASE_OUTPUT/merged_df.tsv" >> "$LOG_FILE" 2>&1

echo "EHDN downstream analysis finished at $(date)" | tee -a "$LOG_FILE"
